[package]
name = "aoc-14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
nom = "7.1.1"
anyhow = "1.0.66"
itertools = "0.10.5"
